# Generated by Django 5.1.2 on 2024-10-20 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='O valor não pode ser inferior a 0'), django.core.validators.MaxValueValidator(5, message='O valor não pode ser superior a 5')]),
        ),
    ]
