# Generated by Django 5.1.2 on 2024-10-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0008_alter_actor_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='nationality',
            field=models.CharField(blank=True, choices=[('BRAZIL', 'BR'), ('USA', 'UNITED STATES')], max_length=100, null=True),
        ),
    ]
