# Generated by Django 5.1.2 on 2024-10-24 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0009_alter_actor_nationality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='nationality',
        ),
    ]
